"use client";

import { Meta, StoryObj } from "@storybook/react";
import { Speaker } from "@/components/speaker/Speaker";

const meta: Meta<typeof Speaker> = {
  title: "Speaker",
  component: Speaker,
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
  },
};
export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    profile_photo: {
      id: 1,
      documentId: "doc1",
      name: "Vitalik_Buterin_Profile",
      alternativeText: "Vitalik Buterin",
      caption: "Vitalik Buterin at TechCrunch London 2015",
      width: 400,
      height: 400,
      formats: {
        thumbnail: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg/150px-Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_thumbnail",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_thumbnail",
          path: null,
          size: 10,
          sizeInBytes: 10240,
          width: 150,
          height: 150,
        },
        large: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_large",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_large",
          path: null,
          size: 50,
          sizeInBytes: 51200,
          width: 400,
          height: 400,
        },
        medium: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg/300px-Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_medium",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_medium",
          path: null,
          size: 25,
          sizeInBytes: 25600,
          width: 300,
          height: 300,
        },
        small: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg/200px-Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_small",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_small",
          path: null,
          size: 15,
          sizeInBytes: 15360,
          width: 200,
          height: 200,
        },
      },
      hash: "vitalik_buterin_2015",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 50,
      url: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
      previewUrl: null,
      provider: "wikimedia",
      provider_metadata: null,
      createdat: "2023-01-01T00:00:00.000Z",
      updatedat: "2023-01-01T00:00:00.000Z",
      publishedat: "2023-01-01T00:00:00.000Z",
    },
    name: "Vitalik Buterin",
    url: "https://google.com",
  },
};

export const WithLink: Story = {
  args: {
    profile_photo: {
      id: 2,
      documentId: "doc2",
      name: "Vitalik_Buterin_Profile",
      alternativeText: "Vitalik Buterin",
      caption: "Vitalik Buterin at TechCrunch London 2015",
      width: 400,
      height: 400,
      formats: {
        thumbnail: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg/150px-Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_thumbnail",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_thumbnail",
          path: null,
          size: 10,
          sizeInBytes: 10240,
          width: 150,
          height: 150,
        },
        large: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_large",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_large",
          path: null,
          size: 50,
          sizeInBytes: 51200,
          width: 400,
          height: 400,
        },
        medium: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg/300px-Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_medium",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_medium",
          path: null,
          size: 25,
          sizeInBytes: 25600,
          width: 300,
          height: 300,
        },
        small: {
          ext: ".jpg",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg/200px-Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
          hash: "vitalik_buterin_2015_small",
          mime: "image/jpeg",
          name: "Vitalik_Buterin_Profile_small",
          path: null,
          size: 15,
          sizeInBytes: 15360,
          width: 200,
          height: 200,
        },
      },
      hash: "vitalik_buterin_2015",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 50,
      url: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Vitalik_Buterin_TechCrunch_London_2015_%28cropped%29.jpg",
      previewUrl: null,
      provider: "wikimedia",
      provider_metadata: null,
      createdat: "2023-01-01T00:00:00.000Z",
      updatedat: "2023-01-01T00:00:00.000Z",
      publishedat: "2023-01-01T00:00:00.000Z",
    },
    name: "Vitalik Buterin",
    url: "https://google.com",
  },
};
